# -*- encoding: utf-8 -*-

=begin
#Swagger Petstore

#A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification

The version of the OpenAPI document: 1.0.0
Contact: apiteam@swagger.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "sample-client/version"

Gem::Specification.new do |s|
  s.name        = "sample-client"
  s.version     = SampleClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["mogulla3"]
  s.email       = ["mogulla3@example.com"]
  s.homepage    = "https://github.com/mogulla3/gem-on-gh-packages-sample"
  s.summary     = "Swagger Petstore Ruby Gem"
  s.description = "A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.7"

  s.add_runtime_dependency 'faraday', '>= 1.0.1', '< 3.0'
  s.add_runtime_dependency 'faraday-multipart'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
