=begin
#Swagger Petstore

#abcdef

The version of the OpenAPI document: 1.0.0
Contact: apiteam@swagger.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

module SampleClient
  VERSION = '1.0.0'
end
