name: generate-petstore-client
run-name: Create a PullRequest to update the petstore-ruby-client
on:
  push:
    branches:
      - main
    paths:
      - openapi3.yaml
jobs:
  create-pr:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Generate ruby-client
        run: make generate-client
      - name: Check diff
        id: check_diff
        run: git diff --quiet --exit-code
        continue-on-error: true
      - name: Create PullRequest
        env:
          BRANCH_NAME: build-client-from-${{ github.sha }}
        if: steps.check_diff.outcome == 'failure'
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m 'Update api-client'
          git push origin $BRANCH_NAME
          gh pr create -f -B 'main' -l 'api-client' -t 'Update api-client' -b "Updated api-client to reflect this change: $GITHUB_SHA"
