name: generate-petstore-client
run-name: Create a PullRequest to update the petstore-ruby-client
on:
  push:
    branches:
      - main
    paths:
      - 'openapi3.yaml'
jobs:
  generate-client:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Generate ruby-client
        run: make generate-client
      - name: Check diff
        id: check_diff
        run: git diff --quiet --exit-code
        continue-on-error: true
      - name: Create PullRequest
        env:
          BRANCH_NAME: build-client-from-${{ github.sha }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m 'Generate client.'
          git push origin $BRANCH_NAME
          gh pr create -f -B "main" -t "Update client" -b "" -l "api-client"
        if: steps.check_diff.outcome == 'failure'
